// Import Image Files
import favicon from '../images/favicon-32x32.png';
import profile from '../images/image-jeremy.png';
import iconEllipsis from '../images/icon-ellipsis.svg';
import iconExercise from '../images/icon-exercise.svg';
import iconPlay from '../images/icon-play.svg';
import iconSelfCare from '../images/icon-self-care.svg';
import iconSocial from '../images/icon-social.svg';
import iconStudy from '../images/icon-study.svg';
import iconWork from '../images/icon-work.svg';